# Continuously check builds on every push and pull request

name: Continuous Integration

on: [push, pull_request]

jobs:
  compile:
    runs-on: ubuntu-22.04
    name: Compile
    strategy:
      matrix:
        subgraph:
          [
            'bonds',
            'carbonmark',
            'protocol-metrics',
            'vesting',
            'user-carbon',
            'pairs',
            'celo-bridged-carbon',
            'ethereum-bridged-carbon',
            'polygon-digital-carbon',
          ]
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install root dependencies
        run: npm install
      - name: Install workspace dependencies
        run: npm install
        working-directory: '${{ matrix.subgraph }}'

      # Generate code and check for uncommitted changes
      # https://github.com/marketplace/actions/check-uncommitted-changes
      - name: Prepare Manifest
        if: matrix.subgraph == 'polygon-digital-carbon' || matrix.subgraph == 'carbonmark'
        run: npm run prepare-matic
        working-directory: '${{ matrix.subgraph }}'
      - name: Generate Subgraph Code
        run: npm run codegen
        working-directory: '${{ matrix.subgraph }}'
      - name: Check for uncommitted changes
        id: check-changes
        uses: mskri/check-uncommitted-changes-action@v1.0.1
      - name: Evaluate if there are changes
        if: steps.check-changes.outputs.outcome == failure()
        run: echo "There are uncommitted changes - execute 'npm run codegen' locally and commit the generated files!"

      - name: Build Subgraph
        run: npm run build
        working-directory: '${{ matrix.subgraph }}'
      - name: Run Tests
        if: matrix.subgraph == 'polygon-digital-carbon' || matrix.subgraph == 'carbonmark' || matrix.subgraph == 'pairs'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        run: npm run test -d
        working-directory: '${{ matrix.subgraph }}'
